northpolesec/santa

Source/santad/BUILD, Source/santad/EventProviders/SNTEndpointSecurityClientBase.h, Source/santad/EventProviders/SNTEndpointSecurityTreeAwareClient.mm, Source/santad/EventProviders/SNTEndpointSecurityTreeAwareClientTest.mm
This fixes an issue for tree aware clients that have not enabled any process tree annotations but also do no subscribe to the set of force-enabled tree aware client event types (fork/exec/exit).
Before this change, `handleContextMessage` would always return false when process trees weren't in use. Instead it should return whether or not the event type was force added.
This bug does not currently affect Santa's current implementation as the only tree aware client (the recorder) subscribes to the full set of force-enabled events. But it does affect various debug routines where event subscriptions are manipulated.
This PR also begins including tree aware client tests.
=> Fix tree aware clients handleContextMessage default return

BUILD, Conf/Package/package.sh, Conf/Package/package_and_sign.sh, Conf/Package/postinstall, Conf/Package/preinstall
This CL changes the installer to lay down Santa on disk as Santa_NPS.app. The post install or daemon will rename Santa_NPS.app to Santa.app when it is safe to do so.
A follow up CL will add logic in the daemon to idle while another install of Santa is running.
To test the installer behavior as new label has been added `package-dev`, which will package up a dev build. To support this, `package.sh` is now a separate script that can be called for both release and dev builds.
```
bazel build :package-dev -c opt
```
=> installer: support side-by-side install of NPS Santa [1/2]

Conf/Package/package.sh, Conf/Package/postinstall, Conf/Package/preinstall
This is a partial revert of 338da35. It keeps the `:package-dev` rule, but reverts installing as Santa_NPS.app.
Rebase once https://github.com/northpolesec/santa/pull/26 lands.
=> partial revert: installer: support side-by-side install of NPS Santa [1/2] 

.pyink-config, Source/gui/Info.plist, Source/santabundleservice/Info.plist, Source/santactl/Info.plist, Source/santad/Info.plist, Source/santametricservice/Info.plist, Source/santasyncservice/Info.plist, Testing/lint.sh
This PR updates the copyright statement in the Info.plist of all of the binaries in Santa.
This also updates the `Testing/lint.sh` script to use a virtual environment for python3 and updates the pyink config file to exclude the virtual env directory `./santa-venv`.
=> Update copyright statements for all binaries.

Conf/Package/package_and_sign.sh
As well as publishing a tarball and the package wrapped in a DMG, we will now start publishing the PKG from inside the DMG too, as this is easier to use with many MDMs
=> Packaging: Copy the pkg to the artifact dir

Conf/com.northpolesec.santa.bundleservice.plist, Conf/com.northpolesec.santa.metricservice.plist, Conf/com.northpolesec.santa.migration.plist, Conf/com.northpolesec.santa.plist, Conf/com.northpolesec.santa.syncservice.plist
This change allows the icon for Santa to be properly displayed in the "Login Items & Extensions" settings page for "Allow in Background" items.
=> Set associated BundleIDs in launchd plists

.github/workflows/ci.yml
Also remove the workflow_dispatch option, being able to manually trigger the CI workflow isn't useful, continuous can be used for that instead.
=> Workflows: Use the runner OS as the key for disk caches

.github/workflows/ci.yml
runner.os is always `macOS`, so it doesn't do what we need
=> Project: Use `matrix.os` as cache key instead of `runner.os`

Source/common/SNTBlockMessage.h, Source/common/SNTBlockMessage.m, Source/gui/BUILD, Source/gui/Resources/en.lproj/Localizable.strings, Source/gui/Resources/en.lproj/regen.sh, Source/gui/Resources/ru.lproj/Localizable.strings, Source/gui/Resources/uk.lproj/Localizable.strings, Source/gui/SNTAboutWindowView.swift, Source/gui/SNTBinaryMessageWindowView.swift, Source/gui/SNTDeviceMessageWindowView.swift, Source/gui/SNTFileAccessMessageWindowView.swift
I've included basic translations in Russian and Ukrainian as examples; these translations were generated with a translation tool and checked by a fluent speaker of both so they're good but likely not perfect (improvements welcome!)
There's also a basic shell script included to help generate the base English localization files but manual work will be necessary to merge the output with the checked-in English file and to add/update any missing/changed strings in the other languages.
Before anyone asks: we can't use the newer xcstrings format because:
a) Bazel doesn't support it yet
b) I can't find a tool like genstrings to generate it automatically
Part of #14 and #53
=> GUI: Localization support

Source/gui/SNTBinaryMessageWindowView.swift
When publisher is nil, do not display the "Publisher" label.
=> gui: fix publisher layout

Source/common/SNTBlockMessage.m, Source/gui/Resources/de.lproj/Localizable.strings, Source/gui/Resources/en.lproj/Localizable.strings, Source/gui/Resources/ru.lproj/Localizable.strings, Source/gui/Resources/uk.lproj/Localizable.strings
SNTBlockMessage is used to generate messages in the TTY, where localization won't be applied, so the English version of these strings need to remain the 'key'
=> Localization: Don't use keys in strings in SNTBlockMessage.

Conf/install_services.sh, Source/santad/EventProviders/SNTEndpointSecurityTamperResistance.mm
This PR adds additional protections to the Tamper Resistance client to prevent launchd loads of legacy Santa plists. When these loads are attempted, the legacy plists are also removed from the filesystem if they exist.
Some additional install_services.sh cleanup of legacy components was also added.
=> Prevent legacy service loads, cleanup legacy plists

Source/santad/DataLayer/WatchItemPolicy.h, Source/santad/DataLayer/WatchItems.mm, Source/santad/DataLayer/WatchItemsTest.mm, Source/santad/EventProviders/SNTEndpointSecurityFileAccessAuthorizerTest.mm
Fixes an issue where the UI and TTY messages were using the default "temp_version" string instead of the global policy version string. This was previously left over from some initial work to support per-rule versions for when FAA rules eventually move to the sync protocol.
=> Set FAA per-rule version to the policy version

Source/gui/SNTBinaryMessageWindowController.h, Source/gui/SNTBinaryMessageWindowController.m, Source/gui/SNTBinaryMessageWindowView.swift, Source/gui/SNTNotificationManager.m, Source/santabundleservice/SNTBundleService.m
This CL displays progress while bundle hashing.
While hashing:
More details once complete:
https://github.com/user-attachments/assets/d6556049-0c6f-4311-8c47-d82b2030609d
=> gui: display bundle hashing progress

Source/common/BUILD, Source/common/SNTBlockMessage.h, Source/common/SNTBlockMessage.m, Source/common/SNTConfigurator.m, Source/common/SNTXPCNotifierInterface.h, Source/gui/BUILD, Source/gui/SNTDeviceMessageWindowController.h, Source/gui/SNTDeviceMessageWindowController.m, Source/gui/SNTDeviceMessageWindowView.swift, Source/gui/SNTMessageView.swift, Source/gui/SNTNotificationManager.m, Source/santad/Santad.mm
This involved a lot of non-UI changes around how the block message is generated because this was previously handled partially in santad and partially in the configurator, which made the message un-localizable
=> GUI: Update DeviceMessage to new UI

docs/_config.yml, docs/deployment/migration.md
* Fix the formatting of code blocks - as the blocks didn't have a newline in between they were not being parsed correctly
* Move the "warning" messages into callouts
To preview, run `bundle install && bundle exec jekyll serve` inside the docs folder.
=> docs: Fix formatting in migration doc

Source/santactl/Commands/SNTCommandInstall.mm
This fixes a typo in the `SNTCommandInstall.mm` where we had `waitng` instead of `waiting`
=> Fix typo in install command

Conf/Package/migration.sh, Conf/Package/postinstall, Conf/install_services.sh, Source/santad/EventProviders/SNTEndpointSecurityTamperResistance.mm
This PR adds additional cleanup for two cases:
1. Upgrading from NPS Santa to NPS Santa
The `com.northpolesec.santa.migration.plist` launch daemon artifact was being left on disk. This was due to tamper protections preventing the deletion on installation of the upgraded version. While benign, it's not ideal to leave the artifact on disk. This file is now removed.
2. When Google Santa is attempted to be installed over NPS Santa, the `com.google.santa.newsyslog.conf` artifact was not cleaned up.
During discussion, we decided it would be best that instead of always attempting to remove this file, we should instead mv the contents to the new `com.northpolesec.santa.newsyslog.conf` path. This will help NPS deployments maintain the same configuration as the previous deployments in the rare …
=> Address findings from migration testing

Conf/Package/migration.sh, Conf/Package/package.sh, Conf/Package/postinstall, Conf/Package/preinstall, Conf/com.northpolesec.santa.migration.plist, Conf/install.sh, Source/santactl/Commands/SNTCommandInstall.mm
This change only moves the scratch dir used for migration out of /Library/Caches due to external factors that can cause that directory to be blown away (such as OS upgrades).
=> Move away from /Library/Caches for migration

Source/santad/EventProviders/SNTEndpointSecurityTamperResistance.mm
`unlinkat(2)` didn't gain support for `AT_SYMLINK_NOFOLLOW_ANY` until macOS 14. Don't set this flag on earlier OS versions.
=> Only set AT_SYMLINK_NOFOLLOW_ANY on supported OS versions

MODULE.bazel, Source/common/CertificateHelpers.m, Source/gui/BUILD, Source/gui/SNTBinaryMessageWindowView.swift
Firstly, limit the width of the publisher field so it can only grow to a max size and add the full text in a tooltop to allow the full string to be seen if needed.
Secondly, if the publisher field is a 'Developer ID Application' cert, don't show the OrgName and CommonName fields as the OrgName is really the useful part
=> GUI: Prevent publisher from expanding UI too much

Source/santad/BUILD, Source/santad/EventProviders/EndpointSecurity/EnrichedTypes.h, Source/santad/EventProviders/EndpointSecurity/Enricher.h, Source/santad/EventProviders/EndpointSecurity/Enricher.mm, Source/santad/EventProviders/SNTEndpointSecurityRecorder.mm, Source/santad/EventProviders/SNTEndpointSecurityRecorderTest.mm, Source/santad/Logs/EndpointSecurity/Serializers/BasicString.h, Source/santad/Logs/EndpointSecurity/Serializers/BasicString.mm, Source/santad/Logs/EndpointSecurity/Serializers/Empty.h, Source/santad/Logs/EndpointSecurity/Serializers/Empty.mm, Source/santad/Logs/EndpointSecurity/Serializers/Protobuf.h, Source/santad/Logs/EndpointSecurity/Serializers/Protobuf.mm, Source/santad/Logs/EndpointSecurity/Serializers/Serializer.h, Source/santad/Metrics.mm, Source/santad/MetricsTest.mm
This PR starts adding in support for new authentication event types. Protobuf/string serialization will come in future PRs.
The main goal is to define the new enriched types and handle them in the enricher.
=> Subscribe to authentication event types and handle enrichment

Source/santad/DataLayer/WatchItemPolicy.h, Source/santad/DataLayer/WatchItems.h, Source/santad/DataLayer/WatchItems.mm, Source/santad/DataLayer/WatchItemsTest.mm, Source/santad/EventProviders/SNTEndpointSecurityFileAccessAuthorizer.mm, Source/santad/EventProviders/SNTEndpointSecurityFileAccessAuthorizerTest.mm, docs/deployment/file-access-auth.md
`InvertProcessExceptions` is being deprecated in favor of a new `RuleType` config option. This PR defines two RuleType values to keep parity with previous configs:
* `PathsWithAllowedProcesses`: Equates to `InvertProcessExceptions` being set to `false`
* `PathsWithDeniedProcesses`: Equates to `InvertProcessExceptions` being set to `true`
This new configuration is being introduced to support upcoming process-centric FAA rules.
=> Add RuleType FAA config to replace InvertProcessExceptions

Source/common/SNTBlockMessage.m, Source/common/SNTConfigurator.h, Source/common/SNTConfigurator.m, Source/gui/BUILD, Source/gui/SNTBinaryMessageWindowView.swift, Source/gui/SNTTestGUI.swift, Testing/localization.py
So far this is mostly useful for the Binary message window, though there is some rudimentary support for Device messages too. Before I finish that I wanted to get something up.
Run with `bazel run //Source/gui:SNTTestGUI`
=> GUI: Add SNTTestGUI for doing manual testing of the UI

Source/common/SNTConfigurator.m, Source/santasyncservice/SNTSyncService.m, Source/santasyncservice/main.m
Previously we had limited watching for config changes to only `com.northpolesec.santa.daemon`. This was because the other major consumer, `santasyncservice`, received an empty config when the config changed. It turns out this was due to the `NSUserDefaults`, by way of the `SNTConfigurator` singleton, being initialized before `santasyncservice` drops its root privileges.
This CL enables `santasyncservice`, and the other services, to watch for config changes.
It also fixes the bug described above in `santasyncservice`, `SNTConfigurator` is now initialized after dropping privileges.
=> config: services now watch for config changes

Source/gui/SNTBinaryMessageWindowView.swift
=> GUI: Fix rendering of long filenames in More Details

Source/common/BUILD, Source/santad/DataLayer/SNTDatabaseTable.h, Source/santad/DataLayer/SNTDatabaseTable.m, Source/santad/DataLayer/SNTRuleTable.h, Source/santad/DataLayer/SNTRuleTable.m, Source/santad/DataLayer/SNTRuleTableTest.m, Source/santad/Logs/EndpointSecurity/Writers/FSSpool/BUILD, Source/santad/ProcessTree/BUILD
This PR fixes an issue with the SNTRuleTable's `currentSupportedVersion` method returning the incorrect value due to the constant it wraps not being updated. 
It makes the `currentSupportedVersion` method part of the interface, so as to expose for testing and metrics. 
A unit test is added to ensure that this constant is updated in the future.
This  bug was introduced in #123 was causing all rules to be dropped across builds / restarts.
This PR also adds the imports for the BUILD files to satisfy the linter.
=> Fix: Database Rule Table Version number

Source/santad/DataLayer/SNTRuleTableTest.m
Instead of checking a constant version (which will require updating the test each time we update the constant) this compares the version returned from an initialized database against the maximum version supported by the table class
=> Tests: Simplify SNTRuleTableTest

Source/common/SNTConfigurator.h, Source/common/SNTConfigurator.m, Source/gui/SNTBinaryMessageWindowView.swift, Source/gui/SNTMessageView.swift, docs/concepts/mode.md, docs/deployment/configuration.md
This makes standalone mode usable in clamshell mode or on a desktop machine.
This change also modifies the authorization dialog for unsigned, non-bundled binaries to just show the binary name instead of the full path. In many cases the full path is very long and as the dialog is limited in width it makes the path squash up and become nearly unreadable.
=> standalone: Allow password fallback

Source/santad/DataLayer/SNTRuleTable.m, Source/santad/DataLayer/SNTRuleTableTest.m, Source/santad/SNTExecutionControllerTest.mm, Source/santad/SNTPolicyProcessor.mm
This PR adds signing ID checks for critical system binaries in addition to the hash check. 
In some scenarios e.g. a Santa upgrade in lockdown mode you may have two versions of the critical binary that needs to run on the system. This ensures that the later can run.
=> Fix: Add signing ID checks for critical binaries

MODULE.bazel, Source/common/BUILD, Source/common/EncodeEntitlements.h, Source/common/EncodeEntitlements.mm, Source/common/EncodeEntitlementsTest.mm, Source/common/SNTStoredEvent.h, Source/common/SNTStoredEvent.m, Source/santad/BUILD, Source/santad/Logs/EndpointSecurity/Serializers/Protobuf.mm, Source/santad/SNTExecutionController.mm, Source/santasyncservice/BUILD, Source/santasyncservice/SNTSyncEventUpload.mm
This PR also updates MODULES.bazel to pull in https://github.com/northpolesec/protos/pull/12
=> Add entitlements to sync protocol

Source/gui/SNTTestGUI.swift
The verbatim labels allows you to run the TestGUI with e.g. `-AppleLanugages '(ja)'` to test the Santa UI with localization while the TestGUI itself will remain in English
=> TestGUI: Fix missing replyCallback, make labels in UI verbatim.

Source/santad/BUILD, Source/santad/DataLayer/WatchItemPolicy.h, Source/santad/DataLayer/WatchItems.h, Source/santad/DataLayer/WatchItems.mm, Source/santad/DataLayer/WatchItemsTest.mm, Source/santad/EventProviders/SNTEndpointSecurityFileAccessAuthorizer.mm, Source/santad/EventProviders/SNTEndpointSecurityFileAccessAuthorizerTest.mm
This PR starts the process of breaking up `WatchItemPolicy` into `DataWatchItemPolicy` and `ProcessWatchItemPolicy` to as a first step in implementing Proc FAA.
`WatchItems` is also being broken up to abstract out the `DataWatchItems` into their own object so that it can be operated on singularly. A future PR will add `ProcessWatchItems` to work similarly.
=> Restructure Watch Items objects to prepare for Proc FAA

Source/common/SNTConfigurator.m, Source/common/SNTRule.h, Source/common/SNTRule.m, Source/common/SNTRuleTest.m, Source/santactl/Commands/SNTCommandRule.m, Source/santad/SNTPolicyProcessorTest.mm
This PR makes SNTRule's initWithDictionary method case insensitive by normalizing the keys of the dictionary to be lowercase.
This avoids issues like typing `rule_Type` when adding static rules or when importing rules from a JSON file.
=> Make SNTRule initWithDictionary case insensitive

Source/common/CertificateHelpers.h, Source/common/CertificateHelpers.m, Source/common/SNTCachedDecision.h, Source/common/SNTCommonEnums.h, Source/common/SNTStoredEvent.h, Source/common/SNTStoredEvent.m, Source/santad/BUILD, Source/santad/DataLayer/SNTRuleTable.m, Source/santad/SNTExecutionController.mm, Source/santad/SNTPolicyProcessor.mm, Source/santad/SNTPolicyProcessorTest.mm
The main purpose of this PR is to address a crash that could occur in STANDALONE mode when attempting to approve ad hoc signed binaries.
This PR also changes behavior for how to identify which fields are valid for rule lookup. Instead of clearing values form the SNTCachedDecision, the signing status of the executing binary is tracked separately and used to compute valid identifiers. This will allow reporting of all fields in sync events instead of clearing this critical info (separate PR).
=> Rework how valid rule IDs are tracked

Source/santad/Logs/EndpointSecurity/Serializers/BasicString.mm, Source/santad/Logs/EndpointSecurity/Serializers/BasicStringTest.mm, Source/santad/Logs/EndpointSecurity/Serializers/Protobuf.mm, Source/santad/Logs/EndpointSecurity/Serializers/ProtobufTest.mm, Source/santad/testdata/protobuf/v1/clone.json, Source/santad/testdata/protobuf/v2/clone.json, Source/santad/testdata/protobuf/v4/clone.json, Source/santad/testdata/protobuf/v4/copyfile.json, Source/santad/testdata/protobuf/v5/clone.json, Source/santad/testdata/protobuf/v5/copyfile.json, Source/santad/testdata/protobuf/v6/clone.json, Source/santad/testdata/protobuf/v6/copyfile.json, Source/santad/testdata/protobuf/v7/clone.json, Source/santad/testdata/protobuf/v7/copyfile.json, Source/santad/testdata/protobuf/v8/clone.json, Source/santad/testdata/protobuf/v8/copyfile.json
The bulk of the PR is new test golden files.
The main thing to call out is that the string serialization doesn't include "mode", "flags", and "previously existed" like is done for proto. This is largely because encoding these types is more cumbersome. We often don't add these for the string serializations, but could add them (maybe as hex and true/false strings?) if anyone feels strongly.
=> Add serializations for clone and copyfile

Source/santad/SNTDaemonControlController.mm
Because install.sh (and postinstall) now use output from `santactl status`, this CL also fixes the intermittent hanging we have noticed during `bazel :reload`.
https://github.com/northpolesec/santa/blob/ce65385ca5234e071bdefac96cbf9ef46ff69605/Conf/install.sh#L40
=> santactl status: fix hang when sync server is unresponsive

docs/deployment/migration.md
This PR adds an optional step of adding a `Team ID` rule for NPS to Google Santa in the migration guide.
=> Add an optional step to add a TeamID rule for NPS Santa

Source/common/santa.proto
This is, among other places, documented in the ESMessage.h header, where it says that (pid, pidversion) "is not meant to be unique across reboots or across multiple systems".
=> Clarify uniqueness properties of PID + pidversion

Source/santad/SNTExecutionController.mm, Source/santad/SNTNotificationQueue.h, Source/santad/SNTNotificationQueue.mm, Source/santad/SNTNotificationQueueTest.mm, docs/known-limitations.md
This change makes it so that not only are the pending blocks responded to with a FALSE argument, but the notifications themselves are also cleared from the queue.
Previously, the notifications were left  in the queue to replicate behavior similar to LOCKDOWN mode where the user would be notified of blocks that occurred while not logged in and allow them to remedy the situation.
However for standalone mode, the reply blocks were getting cleared, but leaving the notification intact. This resulted in the user being notified about the block event and given the option to approve the binary. However since the reply block was cleared, santad would take no action and no rule would be created. This would be confusing to users.
Some better potential long term fixes would be to add additional …
=> Remove pending standalone notifications on UI connection invalidation

Source/santad/DataLayer/WatchItems.mm, Source/santad/DataLayer/WatchItemsTest.mm
Fixes an issue where configured non-glob watch paths (i.e. those without any glob magic characters) in FAA rules would not be monitored until after the file was created and Santa re-applied the config to see the new path (default 10m, defined by `FileAccessPolicyUpdateIntervalSec`).
=> Ensure that non-glob faa path patterns are watched

Source/common/SNTConfigurator.m
Nothing in this plist is sensitive and preventing the non-root procs from reading it can cause config mismatches
=> Config: Adjust perms to 0644 for sync-state.plist.

Conf/uninstall.sh
Forget receipt for tools (e.g. Munki) that may depend on the receipt to determine installation status.
=> Include line to forget receipt

Source/common/SNTSystemInfo.m, Source/common/santa.proto, Source/santad/BUILD, Source/santad/Logs/EndpointSecurity/Serializers/Protobuf.mm
Fixes #211 
```
[
{
"event_time": "2025-01-29T15:45:09.171590Z",
"processed_time": "2025-01-29T15:45:09.171590Z",
"boot_session_uuid": "aa3fade9b04741bd972df8ab4f003e96",
"disk": { ... }
},
{
"event_time": "2025-01-29T15:45:12.305985602Z",
"processed_time": "2025-01-29T15:45:12.319282Z",
"boot_session_uuid": "aa3fade9b04741bd972df8ab4f003e96",
"execution": { ... }
},
...
]
```
=> Add boot session uuid to proto event logs

Source/santactl/SNTCommandController.m, docs/deployment/troubleshooting.md
```
$ santactl status
An error occurred communicating with the Santa daemon. Check to make sure
the process is running and has been granted Full Disk Access permissions.
For detailed steps, see: https://northpole.dev/deployment/troubleshooting
```
=> Print troubleshooting steps when santactl cannot connect to daemon

Source/santad/BUILD, Source/santad/DataLayer/WatchItemPolicy.h, Source/santad/DataLayer/WatchItemPolicyTest.mm, Source/santad/DataLayer/WatchItems.h, Source/santad/DataLayer/WatchItems.mm, Source/santad/DataLayer/WatchItemsTest.mm, Testing/fix.sh
This adds the ability to parse new Proc-based FAA rules. They are not yet used.
There are some types that will need to change that affect both the proc- and data-based FAA rules, but that work is saved for the next PR to keep the size here sane.
=> Add support for parsing new proc-based FAA rules

Source/santad/DataLayer/WatchItemPolicy.h, Source/santad/DataLayer/WatchItemPolicyTest.mm, Source/santad/DataLayer/WatchItems.h, Source/santad/DataLayer/WatchItems.mm, Source/santad/DataLayer/WatchItemsTest.mm, Source/santad/EventProviders/SNTEndpointSecurityClient.mm, Source/santad/EventProviders/SNTEndpointSecurityClientBase.h, Source/santad/EventProviders/SNTEndpointSecurityClientTest.mm, Source/santad/EventProviders/SNTEndpointSecurityEventHandler.h, Source/santad/EventProviders/SNTEndpointSecurityFileAccessAuthorizer.mm, Source/santad/EventProviders/SNTEndpointSecurityFileAccessAuthorizerTest.mm, Source/santad/EventProviders/SNTEndpointSecurityTamperResistance.mm
The goal of this PR is to better represent data with types that match how the FAA configuration is understood. This largely means things like converting vectors to sets to ensure no duplicate data.
Some additional tests were added, but there are no new features with this change.
Finally, type alias names were standardized for better readability.
=> Better type representation in FAA, standardize type alias naming

Source/common/BUILD, Source/common/TelemetryEventMap.h, Source/common/TelemetryEventMap.mm, Source/common/TelemetryEventMapTest.mm, Source/common/santa.proto, Source/santad/BUILD, Source/santad/EventProviders/EndpointSecurity/EnrichedTypes.h, Source/santad/EventProviders/EndpointSecurity/Enricher.mm, Source/santad/EventProviders/SNTEndpointSecurityRecorder.mm, Source/santad/EventProviders/SNTEndpointSecurityRecorderTest.mm, Source/santad/Logs/EndpointSecurity/Serializers/BasicString.h, Source/santad/Logs/EndpointSecurity/Serializers/BasicString.mm, Source/santad/Logs/EndpointSecurity/Serializers/Empty.h, Source/santad/Logs/EndpointSecurity/Serializers/Empty.mm, Source/santad/Logs/EndpointSecurity/Serializers/Protobuf.h, Source/santad/Logs/EndpointSecurity/Serializers/Protobuf.mm, Source/santad/Logs/EndpointSecurity/Serializers/Serializer.h, Source/santad/Metrics.mm, Source/santad/MetricsTest.mm
Adds support for the Gatekeeper Override ES event type. Serialization support will come in a followup PR to keep sizes smaller.
Part of: #129
=>  Add support for Gatekeeper Override event

Makefile, Source/santad/BUILD, Source/santad/DataLayer/WatchItems.h, Source/santad/DataLayer/WatchItems.mm, Source/santad/EventProviders/EndpointSecurity/EndpointSecurityAPI.h, Source/santad/EventProviders/EndpointSecurity/EndpointSecurityAPI.mm, Source/santad/EventProviders/SNTEndpointSecurityAuthorizer.h, Source/santad/EventProviders/SNTEndpointSecurityAuthorizer.mm, Source/santad/EventProviders/SNTEndpointSecurityClient.mm, Source/santad/EventProviders/SNTEndpointSecurityClientBase.h, Source/santad/EventProviders/SNTEndpointSecurityEventHandler.h, Source/santad/EventProviders/SNTEndpointSecurityFileAccessAuthorizer.h, Source/santad/EventProviders/SNTEndpointSecurityFileAccessAuthorizerTest.mm, Source/santad/EventProviders/SNTEndpointSecurityProcessFileAccessAuthorizer.h, Source/santad/EventProviders/SNTEndpointSecurityProcessFileAccessAuthorizer.mm, Source/santad/EventProviders/SNTEndpointSecurityProcessFileAccessAuthorizerTest.mm, Source/santad/Metrics.h, Source/santad/Metrics.mm, Source/santad/MetricsTest.mm, Source/santad/Santad.mm
This PR lays the foundation for the new Proc FAA client and sets up some of the required interfaces between it and the Authorizer client and the WatchItems class. It also implements newly required ES API interfaces. None of this new code is yet hooked up to the rest of Santa - no new client will be created yet at runtime.
Part of: #124
=> Initial infrastructure for Proc FAA client

Source/santad/BUILD, Source/santad/DataLayer/WatchItems.h, Source/santad/DataLayer/WatchItems.mm, Source/santad/EventProviders/EndpointSecurity/EndpointSecurityAPI.mm, Source/santad/EventProviders/SNTEndpointSecurityClient.mm, Source/santad/EventProviders/SNTEndpointSecurityEventHandler.h, Source/santad/EventProviders/SNTEndpointSecurityFileAccessAuthorizer.mm, Source/santad/EventProviders/SNTEndpointSecurityProcessFileAccessAuthorizer.h, Source/santad/EventProviders/SNTEndpointSecurityProcessFileAccessAuthorizer.mm, Source/santad/Santad.mm
This PR sets the stage for the probe interface to do meaningful work by hooking it up to the exec authorizer client as well as adding the interfaces in WatchItems to support iterating policies.  The "block taking a block" design is to mitigate the need for the WatchItems class to be aware of EndpointSecurity, and keeps policy matching in the FAA clients.
Next PR will begin abstracting functions from the existing Data FAA client for reuse in the Proc FAA client.
=> Proc FAA - hookup probe and proc policy iteration interfaces

Source/common/MOLAuthenticatingURLSession.m, Source/common/MOLCertificate.m, Source/santad/ProcessTree/BUILD, Source/santasyncservice/SNTSyncRuleDownload.mm
The only warnings this leaves behind are for the uses of SecAsn1, which is deprecated but Apple offers no alternative for.
=> Project: Fix most deprecation warnings

Source/common/BUILD, Source/common/PrefixTree.h, Source/common/PrefixTreeTest.mm
Adds a new `Contains` method to the `PrefixTree` which will return true if the tree contains any prefix or literal string that matches the input, otherwise false.
=> Add Contains method to PrefixTree

Source/santactl/Commands/SNTCommandFileInfo.m
Entitlements will be printed if `--entitlements` is passed as a flag or if `Entitlements` is in the list of requested keys.
=> santactl/fileinfo: Add --entitlements flag and key.

Source/common/SNTCommonEnums.h, Source/santad/BUILD, Source/santad/EventProviders/EndpointSecurity/Message.h, Source/santad/EventProviders/EndpointSecurity/Message.mm, Source/santad/Metrics.h, Source/santad/Metrics.mm, Source/santad/MetricsTest.mm, Source/santad/SNTExecutionController.mm, Source/santad/SNTPolicyProcessor.h, Source/santad/SNTPolicyProcessor.mm
This removes the metrics collection that was largely added here:
* https://github.com/google/santa/pull/1348
* https://github.com/google/santa/pull/1354
=> Remove stat change detection metrics that are no longer necessary

Source/santad/EventProviders/FAAPolicyProcessor.h, Source/santad/EventProviders/FAAPolicyProcessor.mm, Source/santad/EventProviders/FAAPolicyProcessorTest.mm, Source/santad/EventProviders/SNTEndpointSecurityProcessFileAccessAuthorizer.mm
This PR moves checking target paths into the `CheckIfPolicyMatchesBlock` block to support inverted Proc FAA rules. ES cacheability is also now supported when possible.
=> Support invert Proc FAA rules and ES layer caching when possible

Source/santad/Logs/EndpointSecurity/Serializers/Utilities.mm
This fixes a long-standing issue where the DMG path is not always collected for disk telemetry events depending on how the disk was mounted.
=> Add fallback methods for gathering mounted DMG path

Source/common/SantaCache.h, Source/common/SantaCacheTest.mm
The new `update` method operates similarly to `set` in the following ways:
1. A new element will be created if it doesn't already exist
2. If the element exists the value will be updated (or at least the update block called for the opportunity to be updated)
3. If the cache is at capacity, it will first be cleared prior to the addition of a new element.
This PR also fixes test-only leaks. SantaCacheTest.xctest now runs with no reported leaks under the `leaks(1)` command.
=> Add update method to SantaCache to update value under lock

Source/common/SantaSetCache.h, Source/santad/BUILD, Source/santad/EventProviders/FAAPolicyProcessor.h, Source/santad/EventProviders/FAAPolicyProcessor.mm, Source/santad/EventProviders/MockFAAPolicyProcessor.h, Source/santad/EventProviders/SNTEndpointSecurityFileAccessAuthorizer.h, Source/santad/EventProviders/SNTEndpointSecurityFileAccessAuthorizer.mm, Source/santad/EventProviders/SNTEndpointSecurityProcessFileAccessAuthorizer.h, Source/santad/EventProviders/SNTEndpointSecurityProcessFileAccessAuthorizer.mm, Source/santad/EventProviders/SNTEndpointSecurityProcessFileAccessAuthorizerTest.mm, Source/santad/Santad.mm
This PR adds reads cache to the FAA policy processor. Because moving the cache to this layer will require differentiating between Data and Proc FAA clients, a new `FAAPolicyProcessorProxy` class is introduced that is appropriately subclassed and hides the details of setting the proper FAAClientType enum so that callers cannot accidentally use the wrong value.
=> Add reads cache support to the FAA Policy Processor

MODULE.bazel, Source/common/santa.proto, Source/santad/BUILD, Source/santad/Logs/EndpointSecurity/LoggerTest.mm, Source/santad/Logs/EndpointSecurity/Serializers/BasicString.h, Source/santad/Logs/EndpointSecurity/Serializers/BasicString.mm, Source/santad/Logs/EndpointSecurity/Serializers/BasicStringTest.mm, Source/santad/Logs/EndpointSecurity/Serializers/Empty.h, Source/santad/Logs/EndpointSecurity/Serializers/Empty.mm, Source/santad/Logs/EndpointSecurity/Serializers/Protobuf.h, Source/santad/Logs/EndpointSecurity/Serializers/Protobuf.mm, Source/santad/Logs/EndpointSecurity/Serializers/ProtobufTest.mm, Source/santad/Logs/EndpointSecurity/Serializers/Serializer.h, Source/santad/Logs/EndpointSecurity/Serializers/Serializer.mm, Source/santad/testdata/protobuf/v6/file_access.json, Source/santad/testdata/protobuf/v7/file_access.json, Source/santad/testdata/protobuf/v8/file_access.json
It is possible for a single operation to emit multiple FileAccess telemetry log messages if multiple rules are violated. This PR adds an Operation ID (e.g. "fingerprint") value that would allow consumers of telemetry to link all telemetry from a single operation.
=> Add Operation ID / fingerprint hash to FileAccess telemetry events

Source/santad/EventProviders/FAAPolicyProcessorTest.mm
Method `initWithBinaryPath` is never called in this test. `OCMExpect` on unused method causes test failure in custom OCMock implementation. 
Verified with
```
OCMReject([self.cscMock initWithBinaryPath:OCMOCK_ANY]);
```
=> Remove unused OCMExpect from test

Source/santad/BUILD, Source/santad/EventProviders/FAAPolicyProcessor.h, Source/santad/EventProviders/FAAPolicyProcessor.mm, Source/santad/EventProviders/FAAPolicyProcessorTest.mm, Source/santad/EventProviders/MockFAAPolicyProcessor.h, Source/santad/EventProviders/RateLimiter.h, Source/santad/EventProviders/RateLimiter.mm, Source/santad/EventProviders/RateLimiterTest.mm, Source/santad/EventProviders/SNTEndpointSecurityProcessFileAccessAuthorizerTest.mm, Source/santad/Metrics.h, Source/santad/Metrics.mm, Source/santad/MetricsTest.mm, Source/santad/Santad.mm
FAA logs are now rate limited. This only applies to the telemetry emitted, not to event processing - meaning block rules are still enforced, but some logging might be dropped.
Metrics that were temporarily removed in #297 are also added back in, and also now apply to both Data and Proc FAA clients (keys: `/santa/file_access_authorizer/log/count` and `/santa/rate_limit_count`).
=> Add back metrics and rate limiting shared across FAA clients

Source/santad/EventProviders/FAAPolicyProcessor.mm
Method are referenced from another file and that, for some compiler settings, causes linker error
=> Remove inline specifier from some FAAPolicyProcessor methods

Source/santad/EventProviders/SNTEndpointSecurityProcessFileAccessAuthorizer.mm, Source/santad/EventProviders/SNTEndpointSecurityProcessFileAccessAuthorizerTest.mm
With this change, when the FAA config changes Santa will now re-evaluate processes that are currently being watched because of the old policies to ensure they should still be watched under the new policies.
This is done by simply clearing the rule cache and having policy lookup be re-triggered the next time some event from a watched process comes in. This also has the nice side effect that cache eviction is now handled the same way.
This also fixes tracking/cleanup issues that existed on FORK/EXEC events.
=> Handle FAA policy changes affecting watched processes

Source/santad/DataLayer/WatchItems.h, Source/santad/EventProviders/SNTEndpointSecurityDataFileAccessAuthorizer.h, Source/santad/EventProviders/SNTEndpointSecurityDataFileAccessAuthorizer.mm, Source/santad/EventProviders/SNTEndpointSecurityDataFileAccessAuthorizerTest.mm, Source/santad/Santad.mm
This change offers better encapsulation since the Data FAA client doesn't need access to the full WatchItems instance.
=> Inject necessary WatchItems method instead of full object

docs/concepts/events.md
=> docs: Correct signing_id format in JSON example

Source/santad/DataLayer/WatchItemPolicy.h, Source/santad/DataLayer/WatchItemPolicyTest.mm, Source/santad/DataLayer/WatchItems.mm, Source/santad/DataLayer/WatchItemsTest.mm, Source/santad/EventProviders/FAAPolicyProcessor.mm, Source/santad/EventProviders/FAAPolicyProcessorTest.mm, docs/deployment/file-access-auth.md
This adds support for a single wildcard character to be used for SigningID values in FAA rules. E.g.
```xml
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
<key>Version</key>
<string>v0.1-experimental</string>
<key>WatchItems</key>
<dict>
<key>UserFoo</key>
<dict>
<key>Paths</key>
<array>
<string>/private/tmp/foo.txt</string>
</array>
<key>Options</key>
<dict>
<key>AllowReadAccess</key>
<false/>
<key>AuditOnly</key>
<true/>
<key>RuleType</key>
<string>PathsWithAllowedProcesses</string>
</dict>
<key>Processes</key>
<array>
<dict>
<key>TeamID</key>
<string>EQHXZ8M8AV</string>
<key>SigningID</key>
<string>com.google.Chrome*</string>
</dict>
</array>
</dict>
</dict>
</dict>
</plist>
```
Related: …
=> Basic wildcard support for FAA SigningID values

Source/santad/Logs/EndpointSecurity/Serializers/BasicStringTest.mm, Source/santad/Logs/EndpointSecurity/Serializers/ProtobufTest.mm
Fixes
```
error: ISO C++ requires field designators to be specified in declaration order; field 'executable_path' will be initialized after field 'item' [-Werror,-Wreorder-init-list]
```
=> Fix ISO C++ field designators declaration order

.bazelrc, Source/santad/Logs/EndpointSecurity/Serializers/BasicStringTest.mm, Source/santad/Logs/EndpointSecurity/Serializers/ProtobufTest.mm
This adds some additional warnings to our build, but disables a subset to allow us to stay on C++17 for now (tho this will likely soon change).
=> Set some additional compiler flags

Source/common/SNTCommonEnums.h, Source/common/SNTXPCSyncServiceInterface.h, Source/common/SNTXPCUnprivilegedControlInterface.h, Source/santactl/Commands/SNTCommandStatus.m, Source/santad/SNTDaemonControlController.mm, Source/santasyncservice/SNTSyncManager.h, Source/santasyncservice/SNTSyncManager.m, Source/santasyncservice/SNTSyncService.mm
This change lets us distinguish in santactl/status output whether push notifications between being disconnected or disabled. This also gives us an easy way to return more statuses in the future, should we need to.
=> santactl/status: better output for push notification status

Source/santad/DataLayer/SNTDatabaseTable.m, Source/santad/DataLayer/SNTEventTable.m, Source/santad/DataLayer/SNTEventTableTest.m
This change adds a unique index to the `filesha256` column in the events table.  This will effectively add deduplication for the same file between either a full sync, or 10 minute local cache (part of SNTSyncdQueue to reduce immediate event uploads for the same file), whichever time is smallest.
**IMPORTANT NOTE**: This will result in the following changes in observed behavior:
1. an overall reduction of events uploaded to the sync server, potentially a large reduction for executables that are executed/blocked frequently
2. When upgrading Santa from a release before this change to after (likely 2025.4), events with duplicate file hashes will be dropped
3. While the `EnableAllEventUpload` has never been about ensuring sync servers see all executions (only evaluated ones), this change will …
=> Add unique index to the filesha256 column in the events table

Source/santad/BUILD, Source/santad/SNTSyncdQueue.mm, Source/santad/SNTSyncdQueueTest.mm
This CL replaces the NSCache used for event upload backoff with SantaCache.
On full cache boundaries, NSCache, has exhibited some odd behavior. Namely, it is possible to get into a situation where a hash is successfully added to the cache, but is immediately cleared. Once in this state, that hash is not able to be successfully retrieved. Even after repeatedly being successfully added to the cache.
If an execution is being blocked in a tight loop like `while true; do yes; done`, this could result in an event being uploaded every [1500ms](https://github.com/northpolesec/santa/blob/82b09a99f3440a9eb6456a859a32905c6e2a5f90/Source/santad/EventProviders/AuthResultCache.h#L58).
Switching to SantaCache gives us better guarantees around full cache boundaries. We know the cache will be cleared when …
=> santad: use santa cache for event upload backoff

Source/common/BUILD, Source/gui/BUILD, Source/santabundleservice/BUILD, Source/santactl/BUILD, Source/santad/BUILD, Source/santametricservice/BUILD, Source/santasyncservice/BUILD
Stop exporting all build rules to the entire project. Allow access in the few places where it's absolutely needed.
=> project: Fix build visibility

Source/common/Platform.h, Source/common/TelemetryEventMap.h, Source/common/TelemetryEventMap.mm, Source/common/TelemetryEventMapTest.mm, Source/common/santa.proto, Source/santad/EventProviders/EndpointSecurity/EnrichedTypes.h, Source/santad/EventProviders/EndpointSecurity/Enricher.mm, Source/santad/EventProviders/SNTEndpointSecurityRecorder.mm, Source/santad/EventProviders/SNTEndpointSecurityRecorderTest.mm, Source/santad/Logs/EndpointSecurity/Serializers/BasicString.h, Source/santad/Logs/EndpointSecurity/Serializers/BasicString.mm, Source/santad/Logs/EndpointSecurity/Serializers/Empty.h, Source/santad/Logs/EndpointSecurity/Serializers/Empty.mm, Source/santad/Logs/EndpointSecurity/Serializers/Protobuf.h, Source/santad/Logs/EndpointSecurity/Serializers/Protobuf.mm, Source/santad/Logs/EndpointSecurity/Serializers/Serializer.h, Source/santad/Metrics.mm, Source/santad/MetricsTest.mm
Adds initial support for the TCC Modify ES event type. Serialization support will come in a followup PR to keep sizes smaller.
Part of #326
=> Add handling for TCC Modify telemetry event

Source/santad/Logs/EndpointSecurity/Serializers/Protobuf.mm, Source/santad/Logs/EndpointSecurity/Serializers/ProtobufTest.mm, Source/santad/testdata/protobuf/v6/launch_item_add.json, Source/santad/testdata/protobuf/v6/launch_item_add_null_app.json, Source/santad/testdata/protobuf/v6/launch_item_add_relative.json, Source/santad/testdata/protobuf/v6/launch_item_add_relative_null_app.json, Source/santad/testdata/protobuf/v7/launch_item_add.json, Source/santad/testdata/protobuf/v7/launch_item_add_null_app.json, Source/santad/testdata/protobuf/v7/launch_item_add_relative.json, Source/santad/testdata/protobuf/v7/launch_item_add_relative_null_app.json, Source/santad/testdata/protobuf/v8/launch_item_add.json, Source/santad/testdata/protobuf/v8/launch_item_add_null_app.json, Source/santad/testdata/protobuf/v8/launch_item_add_relative_null_app.json
Fixes an issue where the wrong info was encoded for the app registrant field in LaunchItem Add events in #322. LaunchItem Remove events were done correctly.
=> Fix serializing wrong field for LaunchItem Add registrant info

BUILD, Source/santad/BUILD, Source/santad/com.northpolesec.santa.daemon.systemextension-debugger.entitlements
This PR adds a new build target that lets you add the `com.apple.security.get-task-allow` entitlement to your Santa builds so you can debug them with lldb or other tools with SIP enabled by adding the `--define=SANTA_BUILD_TYPE=debugger` flag
e.g.
`$  bazel build --define=SANTA_BUILD_TYPE=debugger -c opt //:release`
=> Create a new build and entitlements for live debugging

Source/common/SNTConfigurator.h, Source/common/SNTConfigurator.m, Source/common/SNTConfiguratorTest.m, Source/common/SNTXPCControlInterface.h, Source/santad/SNTDaemonControlController.mm, Source/santasyncservice/BUILD, Source/santasyncservice/SNTSyncService.mm
This changes Santa to persist last stats upload attempt information to help reduce the number of times stats uploads occur. Previously, the sync service would upload on every start and 24 hours later. But if the system rebooted (or even if the service was crash looping) we'd end up uploading far more times than desired.
**Note:** Stats are still opt-in, nothing in this PR changes that.
=> Stats state

Source/santad/SNTNotificationQueueTest.mm
https://clang.llvm.org/extra/clang-tidy/checks/objc/nsinvocation-argument-lifetime.html
=> Fix crashing tests due to incorrect releasing behaviour

Source/santad/Metrics.mm
This fixes the ASAN test failures we get for the `MetricsTests` due to uninitialized memory.
e.g. https://github.com/northpolesec/santa/actions/runs/14430627766/job/40464963126
=> test: Fix the unitialized cache values when using ASAN

Source/common/BUILD, Source/santad/Logs/EndpointSecurity/Writers/FSSpool/BUILD
The `cc_proto_library` rule in rules_cc is deprecated.
=> build: Switch to cc_proto_library from com_google_protobuf

Source/common/BUILD, Source/common/SNTConfigurator.m, Source/santad/BUILD, Source/santad/SNTSyncdQueue.h, Source/santad/SNTSyncdQueue.mm, Source/santad/Santad.mm, Source/santasyncservice/SNTSyncManager.m
This changes Santa to ensure the sync service is running if either a SyncBaseURL is set, or stats collection is enabled. The desired state of the sync service is reassessed whenever configuration is changed to determine if the service should be started, bounced, or stopped.
=> Expand sync service connection state to handle more config keys

BUILD, Makefile
This CL reliably produces compile commands for Santa's source files, including for generated code. This allows clangd to be aware of the various generated interfaces for .proto files, enabling autocomplete and xref links.
https://github.com/user-attachments/assets/d818498a-eecf-4665-a3b2-fe1b1f1bc9c0
=> build: fix clangd visibility for generated code

MODULE.bazel, Source/santasyncservice/SNTSyncRuleDownload.mm, Source/santasyncservice/SNTSyncTest.mm, Source/santasyncservice/testdata/sync_ruledownload_batch1.json, Source/santasyncservice/testdata/sync_ruledownload_batch2.json
This CL adds support for the new notification_app_name field during rule download.
=> rule download: add support for notification app name

Source/gui/SNTFileAccessMessageWindowView.swift, Source/gui/SNTMessageView.swift
Also modify TextWithLimit() to truncate the middle of the string instead of the end
=> gui: truncate accessed path in FAA dialog, add full path to More Details popup

Source/santad/DataLayer/SNTEventTable.m, Source/santad/DataLayer/SNTEventTableTest.m, Source/santad/DataLayer/SNTRuleTable.m
This fixes the following 2 errors, which are both appearing frequently from santad:
```
default	11:38:26.799802-0400	com.northpolesec.santa.daemon	Unknown error calling sqlite3_step (19: UNIQUE constraint failed: events.filesha256) rs
```
```
default	11:38:27.456329-0400	com.northpolesec.santa.daemon	W com.northpolesec.santa.daemon: Unable to compute hash for critical system binary /System/Library/PrivateFrameworks/TCC.framework/Versions/A/Resources/tccd.
```
The first error is because of the unique constraint added in #337 - this causes the transaction to fail if an event is added for a binary that already has a pending event. The desired behavior is that the insert failing is ignored, so adding `ON CONFLICT(filesha256) DO NOTHING` fixes this. `INSERT OR IGNORE` would also work but that …
=> santad: Fix 'UNIQUE constraint failed' and 'Unable to compute hash' errors

docs/docs/deployment/profile-background.md
The example background apps plist was syntactically invalid according to `plutil -lint`.
This appeared to be caused by the `PayloadScope` having no value following it. Moving the value `System` from line `23` up to `18` fixes this.
Also added opening `xml` tag to ensure consistency with other documented examples and fixed up the quotes in the `DOCTYPE` tag.
=> Fixed up background apps plist example

docs/docs/deployment/profile-configuration.md, docs/src/css/custom.css
On the "Profile: Santa Configuration" page, highlight the part of the profile that is _unique_ to Santa, to make it clearer where to put the keys that we document.
While here, also update the container width so that wider windows don't leave half the screen empty and update the "tab width" to 2 spaces so that XML profiles can actually fit on a reasonable size screen.
=> docs: highlight santa profile content, update sizing

Source/gui/BUILD, Source/gui/Resources/de.lproj/Localizable.strings, Source/gui/Resources/en.lproj/Localizable.strings, Source/gui/Resources/ja.lproj/Localizable.strings, Source/gui/Resources/ru.lproj/Localizable.strings, Source/gui/Resources/uk.lproj/Localizable.strings, Source/gui/SNTAboutWindowView.swift, Source/gui/SNTMessageView.swift, Source/gui/SNTTestGUI.swift
Also adds the About window to SNTTestGUI for easier testing.
=> gui: Update about window with new design and default text

docs/docs/deployment/profile-system-extension.md, docs/docs/deployment/profile-tcc.md
This PR updates the UUIDs in the example profiles for the system extension and the TCC profile. 
Related to #379
=> docs: update UUIDs in example profiles to be different than the old Google Santa profiles

Source/gui/BUILD, Source/santabundleservice/BUILD, Source/santactl/BUILD, Source/santad/BUILD, Source/santametricservice/BUILD, Source/santasyncservice/BUILD
This speeds up the build slightly, especially when the timestamp server is busy or when building on a poor connection.
These timestamps are not needed, given that we re-sign every binary when releasing anyway and that signature has its own timestamp.
=> build: Disable codesign timestamp for dev builds

Source/common/SNTConfigurator.m, Source/common/SNTXPCSyncServiceInterface.h, Source/common/SNTXPCUnprivilegedControlInterface.h, Source/common/Timer.h, Source/santactl/BUILD, Source/santactl/Commands/SNTCommandTelemetry.mm, Source/santad/BUILD, Source/santad/Logs/EndpointSecurity/Logger.h, Source/santad/Logs/EndpointSecurity/Logger.mm, Source/santad/Logs/EndpointSecurity/LoggerTest.mm, Source/santad/Logs/EndpointSecurity/MockLogger.h, Source/santad/Logs/EndpointSecurity/Writers/FSSpool/fsspool.cc, Source/santad/Logs/EndpointSecurity/Writers/FSSpool/fsspool.h, Source/santad/Logs/EndpointSecurity/Writers/FSSpool/fsspool_nowindows.cc, Source/santad/Logs/EndpointSecurity/Writers/FSSpool/fsspool_platform_specific.h, Source/santad/Logs/EndpointSecurity/Writers/Spool.h, Source/santad/Logs/EndpointSecurity/Writers/Spool.mm, Source/santad/Logs/EndpointSecurity/Writers/Writer.h, Source/santad/SNTDaemonControlController.mm, Source/santad/SNTSyncdQueue.h, Source/santad/SNTSyncdQueue.mm, Source/santad/Santad.mm, Source/santad/SantadDeps.mm, Source/santasyncservice/SNTSyncService.mm
The PR starts many of the foundational pieces for eventual support for exporting telemetry.
The overall flow is:
1. Export is triggered via a timer in `santad`, or a new `santactl telemetry` command
1.1. If triggered via `santactl`, an XPC message is sent to `santad` to start exporting
2. `santad` will query the configured writer (based on the `EventLogType`) for files to export
1.1.  For each telemetry file, it is first opened
1.2. The file descriptor is sent to the sync service to perform the actual export
* The file descriptor is passed because the sync service doesn't have permissions to read the log files and also ensures logic for handling log files is kept within the daemon
3. When `santad` receives a response from the sync service, it will inform the writer whether or not the …
=> Collect, open, and send telemetry files to sync service for processing

Source/common/MOLXPCConnection.h, Source/common/Platform.h, Source/common/SNTFileInfoTest.m, Source/common/SNTXPCNotifierInterface.h, Source/common/TestUtils.mm, Source/gui/SNTFileAccessMessageWindowController.h, Source/gui/SNTFileAccessMessageWindowView.swift, Source/gui/SNTNotificationManager.m, Source/santad/EventProviders/EndpointSecurity/EndpointSecurityAPI.mm, Source/santad/EventProviders/EndpointSecurity/EnrichedTypes.h, Source/santad/EventProviders/EndpointSecurity/Enricher.mm, Source/santad/EventProviders/SNTEndpointSecurityRecorder.mm, Source/santad/EventProviders/SNTEndpointSecurityRecorderTest.mm, Source/santad/Logs/EndpointSecurity/Serializers/BasicString.h, Source/santad/Logs/EndpointSecurity/Serializers/BasicString.mm, Source/santad/Logs/EndpointSecurity/Serializers/BasicStringTest.mm, Source/santad/Logs/EndpointSecurity/Serializers/Empty.h, Source/santad/Logs/EndpointSecurity/Serializers/Empty.mm, Source/santad/Logs/EndpointSecurity/Serializers/Protobuf.h, Source/santad/Logs/EndpointSecurity/Serializers/Protobuf.mm, Source/santad/Logs/EndpointSecurity/Serializers/ProtobufTest.mm, Source/santad/Logs/EndpointSecurity/Serializers/Serializer.h, Source/santad/Metrics.mm, Source/santad/MetricsTest.mm, Source/santad/Santad.mm
Since we bumped our min supported version to macOS 13, we can remove the runtime and compile time checks for macOS 13 from the codebase.
macOS 12 support dropped here: #399
=> Remove run time and compile time checks for macOS 13

Source/common/MOLXPCConnection.h, Source/common/MOLXPCConnection.m, Source/santad/SNTSyncdQueue.mm, Source/santad/Santad.mm
Also removes deprecated `exportedInterface` that is no longer used.
=> Update how MOLXPCConnection tracks connections, vends proxy objects

Source/common/PrefixTree.h, Source/common/TestUtils.h, Source/santad/DataLayer/WatchItems.mm, Source/santad/DataLayer/WatchItemsTest.mm
This PR changes behavior of FAA path glob expansion.
Previously, this worked rather similarly to shell expansion. Matching paths that existed at the time of application would begin to be watched. A special carve out was made for paths that did not contain glob characters in that they could be watched even if the path didn't exist. This means that only rules with non-glob paths could prevent things like file creation. It could also mean that an FAA rule author might encounter unexpected rules to be matched depending on the state of the filesystem when rules were applied since it could've been the case that some subset of rules were ignored if no path existed.
The new implementation here tries to allow for much more flexible rule application when paths don't exist for paths with glob …
=> FAA glob expansion enhancements

Source/gui/SNTBinaryMessageWindowView.swift, Source/gui/SNTMessageView.swift
1. During bundle hashing the Dismiss button will now show up as "Cancel".
2. During hashing the Open button _will_ be shown but will be disabled, instead of not showing at all.
3. I removed the `bundleProgress` variable from subviews that do not need it
=> gui: change button behavior during hashing

Conf/com.northpolesec.santa.bundleservice.plist
From reading the docs, it seems like this is the correct priority - though in practice I have not noticed a difference in performance or EnablePressuredExit when under load. Doesn't seem to hurt, so let's go for it.
=> bundle service: Adaptive priority

Source/common/BUILD, Source/common/Keychain.h, Source/common/Keychain.mm, Source/common/KeychainTest.mm
This adds objects for Santa to manage store/get/delete operations for keychain items.
The `KeychainManager` is the main class. This will typically be used like a singleton. For Santa's purposes, it will be injected when needed. Consumers of the `KeychainManager` can create `KeychainItem`s for themselves. The `KeychainItem` object then allows users to perform keychain operations for that item.
=> Keychain wrapper implementation

MODULE.bazel, Source/common/MOLCodesignChecker.h, Source/common/MOLCodesignChecker.m, Source/common/SNTCachedDecision.h, Source/common/SNTStoredEvent.h, Source/common/SNTStoredEvent.m, Source/common/StoredEventHelpers.mm, Source/santactl/Commands/SNTCommandFileInfo.m, Source/santad/DataLayer/SNTRuleTable.m, Source/santad/SNTExecutionController.mm, Source/santad/SNTPolicyProcessor.mm, Source/santasyncservice/SNTSyncEventUpload.mm
Adopt the renamed protos and align the naming.
=> Renaming signing timestamp fields

Source/santad/BUILD, Source/santad/DataLayer/SNTRuleTable.mm, Source/santad/DataLayer/SNTRuleTableTest.m, Source/santasyncservice/BUILD, Source/santasyncservice/SNTSyncManager.mm, Source/santasyncservice/SNTSyncRuleDownload.mm, Source/santasyncservice/SNTSyncState.h, Source/santasyncservice/SNTSyncTest.mm
Move CEL expression validation from SNTRuleDownload -> SNTRuleTable so that it applies to both `santactl rule` and rule download. This doesn't cover static rules but that will be coming in a future PR.
Output from rule download failures:
```
Failed to add rule(s) to database: Rule array contained rule with invalid CEL expression
Failure reason: ERROR: <input>:1:1: undeclared reference to 'undefined_field' (in container '')
| undefined_field
| ^
Rule download failed, aborting run
```
Output from santactl sync failures:
```
» sudo santactl rule --force --signingid --identifier platform:com.apple.say --cel 'test'
Failed to modify rules: ERROR: <input>:1:1: undeclared reference to 'test' (in container '')
| test
| ^
```
=> santad: Check CEL expression validity before adding to DB

Source/common/SNTConfigurator.h, Source/common/SNTConfigurator.m, Source/common/SNTRule.h, Source/common/SNTRule.m, Source/common/SNTRuleTest.mm, Source/santactl/Commands/SNTCommandRule.m, Source/santad/DataLayer/SNTRuleTable.h, Source/santad/DataLayer/SNTRuleTable.mm, Source/santad/DataLayer/SNTRuleTableTest.m, Source/santad/SNTDaemonControlController.mm, Source/santad/SNTExecutionController.h, Source/santad/SNTExecutionController.mm, Source/santad/SNTExecutionControllerTest.mm, Source/santad/SNTPolicyProcessor.mm, Source/santad/SNTPolicyProcessorTest.mm, Source/santad/Santad.mm
Use this move to allow checking CEL rules at update time.
=> santad: Move StaticRule processing into SNTRuleTable.

README.md
Switch CI to use shields.io style, update all to flat-square style, update coloring for more consistency. Release related shields are all blue, license is light gray, CI remains green/red based on status.
=> readme: Update shields

Source/common/SNTFileInfo.m, Source/gui/SNTBinaryMessageWindowView.swift
This is a minor UI issue only that is rare and caused by an app developer intentionally setting their bundle name to an empty string. This issue only affects what data Santa chooses to show in the UI, and could result in labels having missing values. There is no missing data in sync events or telemetry.
=> gui: Fix minor UI issue when an app sets empty bundle name

.bazelrc, MODULE.bazel
This is an almost clean revert of #461. `--incompatible_enable_apple_toolchain_resolution` seems to neuter the `--macos_cpus` flag such that our builds are no longer multi-arch. Until we find a better solution, defining the rust toolchains inside this repo and reverting that flag is the easiest fix.
=> build: Fix multi-arch builds for rust

Source/santad/Logs/EndpointSecurity/Serializers/BasicString.mm, Source/santad/Logs/EndpointSecurity/Serializers/BasicStringTest.mm, Source/santad/Logs/EndpointSecurity/Serializers/Protobuf.mm, Source/santad/Logs/EndpointSecurity/Serializers/ProtobufTest.mm
The "not running" reason has not been valid since the old Santa kext was removed. This fixes reason values so that it isn't emitted and rewrites helper functions so that compiler errors will be emitted when new event states are added without properly updating the helpers and associated tests.
=> Fix reason values in exec logs

docs/docs/cookbook/cel.md
This adds a rule for preventing users from disabling gatekeeper via spctl.
=> Cookbook: Add CEL rule to prevent users from disabling gatekeeper

.bazelrc, Source/common/SNTStoredEvent.h, Source/common/SNTStoredExecutionEvent.h, Source/common/SNTStoredExecutionEvent.mm, Source/common/SNTStoredFileAccessEvent.h, Source/common/SNTStoredFileAccessEvent.mm, Source/gui/SNTBinaryMessageWindowView.swift, Source/gui/SNTFileAccessMessageWindowView.swift
This fixes a crash that could occur in the FAA block dialog. This issue was introduced during development of the .7 release and was never part of a release.
=> Add nullability to stored events. Fix unwrap of missing data.

docs/docs/features/binary-authorization.md
This adds the section on rule layering back to the documentation on northpole.dev
=> docs: Add rule layering section back to the docs

.bazelrc, Source/santad/Logs/EndpointSecurity/Writers/FSSpool/AnyBatcher.mm
The `SANTA_OPEN_SOURCE` macro is a vestige of supporting older protobuf library versions in different build environments and is no longer necessary.
=> Remove unnecessary build macro

Source/common/ScopedFile.h, Source/common/ScopedFileTest.mm, Source/santactl/BUILD, Source/santactl/Commands/SNTCommandPrintLog.mm
This PR extends `santactl printlog` to first determine if any of the given files were compressed, and decompress them before deserializing.
=> Support compressed stream in santactl printlog

docs/docs/cookbook/faa.md
Update cookbook rules for blocking access to Slack cookies to include the helper binary and alternate paths for the cookies.
https://github.com/user-attachments/assets/1f82c617-9684-472c-8095-3f90ae7b3b87
=> Cookbook: Update slack rules to better handle helper binaries

Source/santad/Logs/EndpointSecurity/Logger.mm, Source/santad/Logs/EndpointSecurity/LoggerTest.mm
The dot is added in the format string.
=> telemetry export: remove extra dot from file extension

Makefile
This adds a new build target `devrelease` to the Makefile for quickly building a development package for testing install.sh
=> Add a make target for making dev releases

Source/common/BUILD, Source/common/SNTFileAccessRule.h, Source/common/SNTFileAccessRule.mm, Source/common/SNTXPCControlInterface.h, Source/common/SNTXPCControlInterface.mm, Source/santactl/Commands/SNTCommandRule.mm, Source/santad/BUILD, Source/santad/SNTDaemonControlController.mm, Source/santasyncservice/SNTSyncRuleDownload.mm, Source/santasyncservice/SNTSyncTest.mm
This PR sets up the plumbing to get the newly parsed FAA rules over to the daemon.
=> Support sending FAA rules over XPC from sync service to daemon

MODULE.bazel, Source/santasyncservice/SNTSyncPostflight.mm, Source/santasyncservice/SNTSyncRuleDownload.mm, Source/santasyncservice/SNTSyncState.h
This provides matching functionality to existing execution rule counts
=> Add FAA rules received and processed counts

Source/common/SNTConfigurator.h, Source/common/SNTConfigurator.mm, Source/santad/BUILD, Source/santad/EventProviders/FAAPolicyProcessor.h, Source/santad/EventProviders/FAAPolicyProcessor.mm, Source/santad/EventProviders/FAAPolicyProcessorTest.mm, Source/santad/EventProviders/MockFAAPolicyProcessor.h, Source/santad/EventProviders/RateLimiter.h, Source/santad/EventProviders/RateLimiter.mm, Source/santad/EventProviders/RateLimiterTest.mm, Source/santad/EventProviders/SNTEndpointSecurityProcessFileAccessAuthorizerTest.mm, Source/santad/Santad.mm, docs/src/lib/santaconfig.ts
Adds two new configuration values to control rate limiting for logs emitted from FAA rule violations:
* `FileAccessGlobalLogsPerSec` (default: 60)
* `FileAccessGlobalWindowSizeSec` (default: 15)
This replaces the previously hard coed values.
Fixes #566
=> Support changing FAA rate limiting variables via configuration

Source/santactl/BUILD, Source/santactl/Commands/SNTCommandFileInfo.mm
For dev signed code, SigningID and TeamID rules are intentionally ignored. This PR changes the `santactl fileinfo` output to indicate if a rule in the database would have matched if the code was prod signed.
For example, the [Hidden Bar](https://github.com/dwarvesf/hidden) app is on the macOS App Store, but also publishes releases on GitHub that are signed with the development cert. If a TeamID/SigningID rule were added for this app, e.g.:
```
$ sudo santactl rule --allow --teamid --identifier W777S7V8TN
```
The updated output for `santactl fileinfo` is:
```
$ santactl fileinfo --key Rule ~/Downloads/Hidden\ Bar.app
None (TeamID rule ignored because code signed with a development certificate.)
```
=> Make fileinfo output helpful when rule was ignored due to dev signed code

Source/common/BUILD, Source/common/Timer.h, Source/common/faa/BUILD, Source/common/faa/WatchItems.h, Source/common/faa/WatchItems.mm, Source/common/faa/WatchItemsTest.mm, Source/santad/Logs/EndpointSecurity/Logger.mm, Source/santad/Logs/EndpointSecurity/LoggerTest.mm, Source/santad/Santad.mm
This PR makes several improvements to the Timer class:
* Now supports defining a max interval in addition to min that is enforced on config changes
* Inherits from `enable_shared_from_this` - this fixes a potential, but never seen issue related to object lifetimes that could occur on shutdown
* An initial startup delay is now configurable by classes that inherit the Timer
The `WatchItems` class now inherits from `Timer` instead of implementing its own. Additionally, `FileAccessPolicyUpdateIntervalSec` can now be dynamically updated.
Finally, a mock issue in the `LoggerTest` was fixed that was emitting warnings.
=> Timer improvements, allow FileAccessPolicyUpdateIntervalSec to be updated dynamically
