Source/santad/EventProviders/SNTEndpointSecurityTamperResistance.mm
Source/santad/EventProviders/SNTEndpointSecurityTamperResistanceTest.mm

santa-driver hasn't been packaged with Santa for a long time

santad: Stop preventing kextload of santa-driver

---

Source/santactl/Commands/SNTCommandInstall.mm
Source/santad/BUILD
Source/santad/SNTDaemonControlController.mm

This PR implements the daemon side logic for the Santa install flow.

Implement daemon install command

---

Source/gui/SNTBinaryMessageWindowView.swift

Main window:
More details modal:
Hover tooltips showing keyboard shortcuts:

GUI: Reduce icon saturation, add keyboard shortcuts as tooltips, move "Copy Details"

---

Source/gui/Resources/de.lproj/Localizable.strings

Initial Localizable.strings file with German translation

GUI: Add support for German localization

---

Conf/install_services.sh
Conf/uninstall.sh
Source/santad/EventProviders/SNTEndpointSecurityTamperResistance.mm
Source/santad/EventProviders/SNTEndpointSecurityTamperResistanceTest.mm
Source/santad/main.mm

This CL protects Santa's service configs.

tamper client: protect service configs

---

Source/common/BUILD
Source/common/SNTBlockMessage.h
Source/common/SNTFileAccessEvent.h
Source/common/SNTFileAccessEvent.m
Source/common/SNTStoredEvent.h
Source/common/SNTStoredEvent.m
Source/gui/BUILD
Source/gui/SNTBinaryMessageWindowView.swift
Source/gui/SNTFileAccessMessageWindowController.m
Source/gui/SNTFileAccessMessageWindowView.swift
Source/gui/SNTMessageView.swift
Source/santad/EventProviders/SNTEndpointSecurityFileAccessAuthorizer.mm

At the same time, update the FAA dialog to match the new style
FAA main view:
FAA "More Details":

GUI: Refactor common UI elements into a single module.

---

Source/gui/Resources/de.lproj/Localizable.strings

Additional German translation strings added

GUI: Updated support file for German localization

---

Source/gui/SNTBinaryMessageWindowView.swift
Source/gui/SNTFileAccessMessageWindowView.swift
Source/gui/SNTMessageView.swift

gui: Make buttons the same width as the checkbox control

---

Source/santactl/BUILD
Source/santactl/Commands/SNTCommandCheckCache.m
Source/santactl/Commands/SNTCommandFlushCache.m
Source/santactl/Commands/SNTCommandInstall.mm

checkcache and flushcache are now hidden commands. Help text updates.

---

Source/common/SNTRule.h
Source/common/SNTRule.m
Source/common/SNTRuleTest.m
Source/common/SNTSyncConstants.h
Source/common/SNTSyncConstants.m
Source/santactl/Commands/SNTCommandRule.m
Source/santad/DataLayer/SNTRuleTable.m

santad/santactl: Add comment field for rules, populate for manual rules

---

Source/common/TestUtils.mm
Source/santad/Logs/EndpointSecurity/Serializers/Protobuf.mm
Source/santad/Logs/EndpointSecurity/Serializers/ProtobufTest.mm
Source/santad/testdata/protobuf/v6/authentication_auto_unlock.json
Source/santad/testdata/protobuf/v6/authentication_auto_unlock_missing_uid.json
Source/santad/testdata/protobuf/v6/authentication_od.json
Source/santad/testdata/protobuf/v6/authentication_token.json
Source/santad/testdata/protobuf/v6/authentication_touchid.json
Source/santad/testdata/protobuf/v6/authentication_touchid_no_uid.json
Source/santad/testdata/protobuf/v7/authentication_auto_unlock.json
Source/santad/testdata/protobuf/v7/authentication_auto_unlock_missing_uid.json
Source/santad/testdata/protobuf/v7/authentication_od.json
Source/santad/testdata/protobuf/v7/authentication_token.json
Source/santad/testdata/protobuf/v7/authentication_touchid.json
Source/santad/testdata/protobuf/v7/authentication_touchid_no_uid.json
Source/santad/testdata/protobuf/v8/authentication_auto_unlock.json
Source/santad/testdata/protobuf/v8/authentication_auto_unlock_missing_uid.json
Source/santad/testdata/protobuf/v8/authentication_od.json
Source/santad/testdata/protobuf/v8/authentication_od_missing_auth_instigator.json
Source/santad/testdata/protobuf/v8/authentication_token.json
Source/santad/testdata/protobuf/v8/authentication_token_missing_auth_instigator.json
Source/santad/testdata/protobuf/v8/authentication_touchid.json
Source/santad/testdata/protobuf/v8/authentication_touchid_missing_auth_instigator.json
Source/santad/testdata/protobuf/v8/authentication_touchid_no_uid.json

Bulk of the PR changes are golden test files

Add protobuf serialization for new authentication events

---

Source/gui/Resources/ja.lproj/Localizable.strings

All strings as of late 2024 AFAICT, spot-checked by Koji Arita.
May have issue on "Prevent future notifications for this application for " because sentence doesn't end that way grammatically in Japanese, trusting that `\n\n`'s & `<br />`'s will be interpreted correctly.

initial Japanese localization

---

MODULE.bazel
Source/santasyncservice/SNTSyncEventUpload.mm

Updates sync proto module to use commit from https://github.com/northpolesec/protos/pull/13

Add signing status and cs flags to sync proto

---

Source/santad/SNTExecutionController.mm

Fixes issue where the incorrect message was being sent to the TTY in standalone mode when an app was blocked.
From:
```
Santa
Unable to hold execution so the process was killed
---
```
To:
```
Santa
This application has been banned
Path:       .../osascript.1
Identifier: e404f09862855173ab4148d178737c1dd6d40cffc7293d60af6f2edadb67fb90
Parent:     zsh (32415)
More info:
https://sync-server-hostname/blockables/e404f09862855173ab4148d178737c1dd6d40cffc7293d60af6f2edadb67fb90
```

Track ask and hold mode atomically while processing an event

---

MODULE.bazel

This version has a fix for https://github.com/bazelbuild/rules_apple/issues/2604

Up rules_apple to 3.16.1 to fix #190

---

Source/common/SNTConfigurator.m

Removed inadvertently here: https://github.com/northpolesec/santa/pull/200

Add back code to watch changes to our defaults domain

---

Source/common/BUILD
Source/common/CoderMacros.h
Source/common/SNTDeviceEvent.m
Source/common/SNTFileAccessEvent.m
Source/common/SNTRule.m
Source/common/SNTRuleIdentifiers.m
Source/common/SNTStoredEvent.m

Standardize encode/decode macros for NSSecureCoding

---

Makefile
Source/common/String.h
Source/common/santa.proto
Source/santad/BUILD
Source/santad/Logs/EndpointSecurity/Serializers/BasicString.mm
Source/santad/Logs/EndpointSecurity/Serializers/BasicStringTest.mm
Source/santad/Logs/EndpointSecurity/Serializers/Protobuf.mm
Source/santad/Logs/EndpointSecurity/Serializers/ProtobufTest.mm
Source/santad/testdata/protobuf/v8/gatekeeper.json
Source/santad/testdata/protobuf/v8/gatekeeper_path_only.json

Add serializations for Gatekeeper Override event

---

docs/development/sync-protocol.md

This PR updates the sync protocol documentation to reflect the additions added in Santa 2025.1

Updated sync-protocol docs for northpole.dev

---

Source/santactl/Commands/SNTCommandStatus.m
Source/santasyncservice/SNTPolaris.mm

Also fixes an issue where `santactl status` hangs if syncservice isn't running

stats: Fix allocation of protobuf message.

---

Source/santad/BUILD
Source/santad/DataLayer/WatchItemPolicy.h
Source/santad/DataLayer/WatchItems.h
Source/santad/DataLayer/WatchItems.mm
Source/santad/EventProviders/FAAPolicyProcessor.h
Source/santad/EventProviders/FAAPolicyProcessor.mm
Source/santad/EventProviders/FAAPolicyProcessorTest.mm
Source/santad/EventProviders/MockFAAPolicyProcessor.h
Source/santad/EventProviders/SNTEndpointSecurityEventHandler.h
Source/santad/EventProviders/SNTEndpointSecurityFileAccessAuthorizer.h
Source/santad/EventProviders/SNTEndpointSecurityFileAccessAuthorizer.mm
Source/santad/EventProviders/SNTEndpointSecurityFileAccessAuthorizerTest.mm
Source/santad/EventProviders/SNTEndpointSecurityProcessFileAccessAuthorizer.h
Source/santad/EventProviders/SNTEndpointSecurityProcessFileAccessAuthorizer.mm
Source/santad/EventProviders/SNTEndpointSecurityProcessFileAccessAuthorizerTest.mm
Source/santad/Santad.mm
Source/santad/SantadDeps.h

With this PR, Proc FAA is functionally complete but several outstanding tasks remain - largely around adding some caches for improved performance, moving the existing Data FAA client over to the new code, porting tests, and removing a bunch of now-duplicative code. However cutting off the PR here as it's large enough. See comments below for places where I call out code that has been moved/duplicated to help make the review smoother while transitioning.
Note: There are many TODOs intentionally left in where future work is still needed.

Proc FAA initial impl

---

docs/deployment/getting-started.md

Completed the TODO reference to update the link to point to the North Pole Santa mobile config file

Update Link Pointer to Mobile Config

---

Source/santad/EventProviders/FAAPolicyProcessor.mm
Source/santad/EventProviders/SNTEndpointSecurityFileAccessAuthorizer.mm

This addresses an FAA issue that could lead to overly caching results at the ES layer, which could result in not all access being logged appropriately. This doesn't affect rules that would deny access, only audit-only rules.

Fix ES layer cacheability issue in Data FAA and Proc FAA

---

Source/common/SNTRule.h
Source/common/SNTRule.m
Source/santad/DataLayer/SNTRuleTable.m
Source/santad/SNTCompilerController.mm
Source/santad/SNTDecisionCache.mm
Source/santad/SNTExecutionController.mm
Source/santasyncservice/SNTSyncRuleDownload.mm
Source/santasyncservice/SNTSyncTest.mm

Standardizes SNTRule initializers and utilizes them for rule download sync stage in order to add identifier value validation.

Downloaded rule identifiers now pass thru value validation

---

docs/_sass/custom/custom.scss

Update docs sidebar colors and link borders

---

MODULE.bazel

Also removes rules_python which is no longer used.

Module version updates

---

docs/concepts/scopes.md
docs/deployment/configuration.md

This updates the warnings about scopes to use a callout so they're more noticeable.

Docs: Update warnings about scopes.

---

.clang-format
Source/common/SantaCache.h
Source/common/SantaCacheTest.mm

Adds new methods to operate on SantaCache key/value pairs while under lock.

Add foreach and clear with block support to SantaCache

---

Source/gui/Resources/de.lproj/Localizable.strings
Source/gui/Resources/en.lproj/Localizable.strings
Source/gui/Resources/ja.lproj/Localizable.strings
Source/gui/Resources/ru.lproj/Localizable.strings
Source/gui/Resources/uk.lproj/Localizable.strings
Source/gui/SNTNotificationManager.m
Testing/localization.py

The translations here are AI-generated, happy to accept contributions fixing them.
Part of #156

gui: Add localization of client mode switch notifications

---

Source/common/SNTXPCControlInterface.h
Source/common/SNTXPCNotifierInterface.h
Source/gui/Resources/de.lproj/Localizable.strings
Source/gui/Resources/en.lproj/Localizable.strings
Source/gui/Resources/ja.lproj/Localizable.strings
Source/gui/Resources/ru.lproj/Localizable.strings
Source/gui/Resources/uk.lproj/Localizable.strings
Source/gui/SNTNotificationManager.m
Source/santad/SNTDaemonControlController.mm
Source/santasyncservice/SNTSyncRuleDownload.mm

gui: localize unblocked app notifications

---

Source/santad/DataLayer/SNTEventTable.m
Source/santasyncservice/SNTSyncEventUpload.mm

The current implementation could have issues with extremely large event databases

Switch event upload implementation from recursive to iterative

---

Source/santasyncservice/SNTSyncRuleDownload.mm

This helps mitigate memory spikes when downloading gigantic rule sets (e.g. hundreds of thousands).

Add autoreleasepool per rule download batch

---

.github/workflows/ci.yml
Source/common/TestUtils.mm
Source/santad/EventProviders/EndpointSecurity/EnrichedTypes.h
Source/santad/EventProviders/EndpointSecurity/MessageTest.mm
Source/santad/EventProviders/SNTEndpointSecurityAuthorizer.mm
Source/santad/EventProviders/SNTEndpointSecurityClientTest.mm
Source/santad/EventProviders/SNTEndpointSecurityDeviceManager.mm
Source/santad/EventProviders/SNTEndpointSecurityTamperResistance.mm
Source/santad/SNTExecutionControllerTest.mm

This matches the version of clang-format used in the macOS 16.3 SDK.

Use clang-format-19 on ubuntu runner

---

README.md

The first description still implied syncing is done by santactl

project: Update README.md

---

Source/common/TestUtils.mm
Source/santad/Logs/EndpointSecurity/Serializers/BasicString.mm
Source/santad/Logs/EndpointSecurity/Serializers/BasicStringTest.mm
Source/santad/Logs/EndpointSecurity/Serializers/Protobuf.mm
Source/santad/Logs/EndpointSecurity/Serializers/ProtobufTest.mm
Source/santad/testdata/protobuf/v8/tcc_modify.json
Source/santad/testdata/protobuf/v8/tcc_modify_null_everything.json
Source/santad/testdata/protobuf/v8/tcc_modify_null_trigger.json
Source/santad/testdata/protobuf/v8/tcc_modify_null_trigger_responsible.json

Add serializations for TCC modification events

---

Source/common/santa.proto
Source/santad/Logs/EndpointSecurity/Serializers/BasicString.mm
Source/santad/Logs/EndpointSecurity/Serializers/BasicStringTest.mm
Source/santad/Logs/EndpointSecurity/Serializers/Protobuf.mm
Source/santad/Logs/EndpointSecurity/Serializers/ProtobufTest.mm
Source/santad/testdata/protobuf/v6/xp_detected.json
Source/santad/testdata/protobuf/v6/xp_remediated.json
Source/santad/testdata/protobuf/v6/xp_remediated_null_token.json
Source/santad/testdata/protobuf/v7/xp_detected.json
Source/santad/testdata/protobuf/v7/xp_remediated.json
Source/santad/testdata/protobuf/v7/xp_remediated_null_token.json
Source/santad/testdata/protobuf/v8/xp_detected.json
Source/santad/testdata/protobuf/v8/xp_remediated.json
Source/santad/testdata/protobuf/v8/xp_remediated_null_token.json

Add serializations for XProtect events

---

Source/gui/Resources/de.lproj/Localizable.strings
Source/gui/Resources/en.lproj/Localizable.strings
Source/gui/Resources/ja.lproj/Localizable.strings
Source/gui/Resources/ru.lproj/Localizable.strings
Source/gui/Resources/uk.lproj/Localizable.strings
Source/gui/SNTBinaryMessageWindowView.swift

Add the Copy Details button to main block window

---

Source/gui/SNTBinaryMessageWindowView.swift

https://github.com/user-attachments/assets/eefefd2f-d405-4962-a061-518b2ddae357

Add animation to copy details button

---

Source/common/SNTBlockMessage.m
Source/gui/Resources/de.lproj/Localizable.strings
Source/gui/Resources/en.lproj/Localizable.strings
Source/gui/Resources/ja.lproj/Localizable.strings
Source/gui/Resources/ru.lproj/Localizable.strings
Source/gui/Resources/uk.lproj/Localizable.strings

Also add missing localizations for "Accessed Path" and "Binary Path"

gui: Update default banned message

---

Source/gui/Resources/en.lproj/Localizable.strings

Accidentally replaced these in #372

gui: Fix labels around time picker

---

Source/santad/Logs/EndpointSecurity/Logger.h
Source/santad/Logs/EndpointSecurity/Logger.mm
Source/santad/Logs/EndpointSecurity/Serializers/BasicString.mm
Source/santad/Logs/EndpointSecurity/Serializers/Protobuf.mm
Source/santad/Logs/EndpointSecurity/Serializers/Serializer.h
Source/santad/Logs/EndpointSecurity/Serializers/Serializer.mm
Source/santad/Santad.mm
docs/src/lib/santaconfig.ts

Support lockless updates to the MachineID value.

Apply Machine ID config updates in real time

---

MODULE.bazel
Source/common/TelemetryEventMapTest.mm

Address build issues with C++20 on older OS versions

---

Source/common/BUILD
Source/common/SNTCommonEnums.h
Source/gui/BUILD
Source/gui/Resources/de.lproj/Localizable.strings
Source/gui/Resources/en.lproj/Localizable.strings
Source/gui/Resources/ja.lproj/Localizable.strings
Source/gui/Resources/ru.lproj/Localizable.strings
Source/gui/Resources/uk.lproj/Localizable.strings
Source/gui/SNTAboutWindowController.m
Source/gui/SNTAboutWindowView.swift

https://github.com/user-attachments/assets/4bf0c7d7-c2d6-4c7b-909f-ea0994a5de46
https://github.com/user-attachments/assets/1ff9fc13-b6fd-4440-ad24-6c8615f20bcd
The "Copy Logs" button in the failure popup will copy all of the logs that would have printed when running `santactl sync`.

gui: Add 'sync' button to About window

---

Source/common/BUILD
Source/common/SNTFileInfo.h
Source/common/SNTFileInfo.m
Source/gui/BUILD
Source/gui/Info.plist
Source/gui/Resources/de.lproj/Localizable.strings
Source/gui/Resources/en.lproj/Localizable.strings
Source/gui/Resources/ja.lproj/Localizable.strings
Source/gui/Resources/ru.lproj/Localizable.strings
Source/gui/Resources/uk.lproj/Localizable.strings
Source/gui/SNTAboutWindowView.swift
Source/gui/SNTAppDelegate.m
Source/gui/SNTBinaryMessageWindowController.m
Source/gui/SNTBinaryMessageWindowView.swift
Source/gui/SNTFileInfoView.swift
Source/gui/SNTMessageView.swift
Source/santactl/Commands/SNTCommandFileInfo.m
helper.bzl

https://github.com/user-attachments/assets/fbde5265-6ff0-40a8-867b-4fa0ac77432e

gui: allow drag & drop on about window or dock icon to get app details

---

Source/gui/SNTBinaryMessageWindowController.m
Source/gui/SNTBinaryMessageWindowView.swift
Source/gui/SNTNotificationManager.m

https://github.com/user-attachments/assets/751ae39c-55f9-4911-a3f3-44a246e9066f

gui: Simplify display of bundle hash progress, animate disappearing

---

.github/workflows/ci.yml

Also run tests on PRs that change files outside Source/

ci: Stop running on all branches

---

Source/common/SNTConfigurator.m
Source/common/SNTRule.h
Source/common/SNTRule.m

```
Path                   : /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
SHA-256                : 7025a2a0452265ba872f425d8b8365a1839a8151ae50321d9ef8bd3eac7d15dd
SHA-1                  : 7df459e3f64b06a0965922f3c67b3a746cc37789
Bundle Name            : Google Chrome
Bundle Version         : 7151.120
Bundle Version Str     : 137.0.7151.120
Team ID                : EQHXZ8M8AV
Signing ID             : EQHXZ8M8AV:com.google.Chrome
CDHash                 : 42edee28bb2277a598af9b4512914d535e71feee
Type                   : Executable (arm64, x86_64)
Code-signed            : Yes
Secure Signing Time    : 2025/06/17 02:03:44 +0000
Signing Time           : 2025/06/17 02:03:44 +0000
Rule                   : Allowed (TeamID, Static)
```

santactl/fileinfo: Identify static rules

---

Source/santactl/Commands/SNTCommandStatus.m

santactl/status: Show status for disabled features

---

docs/src/components/ConfigGenerator/index.tsx
docs/src/lib/santaconfig.ts

Also add support in the config generator for user input for repeated fields.
https://github.com/user-attachments/assets/811d0be3-a41b-45c4-87fe-486da64e2a4d

docs: add owner groups

---

docs/docs/deployment/profile-configuration.md
docs/src/components/ConfigGenerator/plist.ts

Instead of using the mcx_preference_settings format, install the config as a top-level payload with the bundle ID as the PayloadType. This functions the same but is much better presented in the system settings UI.

docs: Update config profile format

---

Source/santad/Logs/EndpointSecurity/Writers/FSSpool/fsspool.h
Source/santad/Logs/EndpointSecurity/Writers/FSSpool/fsspool_test.mm

This PR cleans up leftover files in the spool tmp dir that may have not been completed, such as various error conditions.

Cleanup spool tmp dir on fsspool construction

---

Source/common/SNTXPCSyncServiceInterface.h
Source/common/SNTXPCSyncServiceInterface.mm
Source/santad/Logs/EndpointSecurity/Logger.mm
Source/santad/SNTSyncdQueue.h
Source/santad/SNTSyncdQueue.mm
Source/santasyncservice/SNTStreamingMultipartFormData.h
Source/santasyncservice/SNTStreamingMultipartFormData.mm
Source/santasyncservice/SNTStreamingMultipartFormDataTest.mm
Source/santasyncservice/SNTSyncService.mm

telemetry: stream multiple files

---

docs/docusaurus.config.ts
docs/package.json
docs/pnpm-lock.yaml

Update docs to use our fork of https://github.com/rachfop/docusaurus-plugin-llms until these features are merged.
- https://github.com/rachfop/docusaurus-plugin-llms/pull/18
- https://github.com/rachfop/docusaurus-plugin-llms/pull/17
- https://github.com/rachfop/docusaurus-plugin-llms/pull/16

docs: Temporarily use NPS docusaurus-plugin-llms plugin

---

Source/common/faa/BUILD
Source/common/faa/WatchItemPolicy.h
Source/common/faa/WatchItemPolicyTest.mm
Source/common/faa/WatchItems.mm
Source/common/faa/WatchItemsTest.mm
Source/santad/EventProviders/FAAPolicyProcessor.mm
Source/santad/EventProviders/FAAPolicyProcessorTest.mm
Source/santad/EventProviders/SNTEndpointSecurityProcessFileAccessAuthorizerTest.mm

Also required for FAA rules in the sync protocol.

Support FAA rules with TID:SID notation
